Landing page
kaze-st/capstone pull request #1
Opened 2021-02-07 17:41 UTC by Kevov

Contains basic layout and styling for landing page. Text content and media content (image/icons) not completed.

2021-02-07 20:47 UTC, Kevov commented
Updated media and font

2021-02-08 02:27 UTC, kaze-st requested changes
Make sure to address all the code comments from below.

2021-02-08 02:27 UTC, kaze-st commented on client/src/App.tsx
> +import LandingPage from './landingPage/LandingPage'
You have a typo here `'./LandingPage/LandingPage'`

2021-02-08 02:27 UTC, kaze-st commented on client/src/App.tsx
> +import LandingPage from './landingPage/LandingPage'
```suggestion
import LandingPage from './LandingPage/LandingPage'
```

2021-02-08 02:27 UTC, kaze-st commented on client/src/App.tsx
>  import logo from './logo.svg';
Delete Unused variables

2021-02-08 02:27 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +const LOGO_PATH = "../../public/favicon.ico"
Unused Variable

2021-02-08 02:27 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +                <li>HOME</li>
These are buttons:

So make sure they have 1) aria labels or roles and 2) There is a pointer cursor

2021-02-08 02:27 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +                <img src="./img/landingComputerImg.jpg" aria-hidden="true"></img>
Alt tag missing

2021-02-08 02:27 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +}
Please add a newline after each file
https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2021-02-08 02:27 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +        <button aria-label="log in button" onClick={handleOnClick}>LOG IN</button>
Please add a pointer cursor for all the buttons in this file. 

https://www.w3schools.com/cssref/pr_class_cursor.asp

2021-02-08 02:27 UTC, kaze-st commented on client/src/index.css
> +@import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700&display=swap');
1. Encapsulate the style logic in a separate file. For example, for the landing page make a `landing-page.scss` and put the styles there.
2. Make sure to use SCSS instead of CSS

2021-02-08 02:27 UTC, kaze-st commented on client/src/App.tsx
>  import React from 'react';
Make sure to alphabetically order your imports. Use sort-imports extension for VSCode

2021-02-11 06:04 UTC, Kevov commented on client/src/LandingPage/LandingPage.tsx
> +                <img src="./img/landingComputerImg.jpg" aria-hidden="true"></img>
aria-hidden removes these images from the accessibility tree so alt tags aren't required 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute

2021-02-11 07:22 UTC, kaze-st requested changes
There are still breaking issues that need to be addressed.

2021-02-11 07:22 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +import React, {MouseEvent} from 'react';
Put this folder in another folder called `components`

2021-02-11 07:22 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +import React, {MouseEvent} from 'react';
This still needs to be addressed

2021-02-11 07:22 UTC, kaze-st commented on client/src/App.tsx
> +import LandingPage from './landingPage/LandingPage'
This still needs to be fixed

2021-02-11 07:22 UTC, kaze-st commented on client/src/index.css
> +}
Make sure to add a newline here. You can autoformat it to do that

2021-02-11 07:22 UTC, kaze-st commented on client/src/index.css
> +@import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700&display=swap');
This is not resolved. It is still a `css` file.

2021-02-11 07:22 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +        console.log("Sign Up");
Remove the `console.log()`

2021-02-11 07:22 UTC, kaze-st commented on client/src/LandingPage/LandingPage.tsx
> +        console.log("Log In");
Remove the `console.log()`

2021-02-11 08:28 UTC, kaze-st approved these changes
Small nits to address. Please fix them and merge the branch to main :smile:
:ship:

2021-02-11 08:28 UTC, kaze-st commented on client/src/components/LandingPage/LandingPage.scss
> +
nit No new line at the end of the page. Also extra space at the end

2021-02-11 08:28 UTC, kaze-st commented on client/src/components/LandingPage/LandingPage.scss
> +.logo-and-title {
The indentation of this file is weird. Format it please.

2021-02-11 09:40 UTC, merged