file model + file controller getFiles
kaze-st/capstone pull request #11
Opened 2021-02-28 20:36 UTC by npham24

2021-03-01 03:24 UTC, kaze-st requested changes
Great job in overall. There are some issues that still needs to be addressed.

2021-03-01 03:24 UTC, kaze-st commented on server/src/controllers/FileController.ts
> +		// if 1 of them fail
This is a very good insight. Transactions is needed in this case scenario. Here is something that you can do:
https://thecodebarbarian.com/whats-new-in-mongoose-5-10-improved-transactions.html

2021-03-01 03:24 UTC, kaze-st commented on server/src/controllers/UserController.ts
> +			res.status(400).send('User not found');
Make a `jsonp` call that sends `{message: "your message"}` object
We are trying to make sure that all the error messages are consistent

2021-03-01 03:24 UTC, kaze-st commented on server/src/models/UserModel.ts
> +	ownedFiles: Array<IFile>;
I think it's better to have it with the `object_id` from Mongo rather than `IFile`. Doing this will be memory inefficient

2021-03-01 03:24 UTC, kaze-st commented on server/src/controllers/FileController.ts
> +			// schema because required = true
The idea is good. But I don't think this is what we want.

Here might be a better solution:

https://stackoverflow.com/questions/44320745/in-mongoose-how-do-i-require-a-string-field-to-not-be-null-or-undefined-permitt

2021-03-01 03:24 UTC, kaze-st commented on server/src/controllers/FileController.ts
> +			res.status(400).send('User not found');
Make a `jsonp` call that sends `{message: "your message"}` object
We are trying to make sure that all the error messages are consistent

2021-03-01 03:24 UTC, kaze-st commented on server/src/routes/v1/file.routes.ts
> +				.isIn(['py', 'java'])
Let's make an `string enum` and then return the list of values.

https://github.com/microsoft/TypeScript/issues/17198

2021-03-03 00:04 UTC, kaze-st requested changes

2021-03-03 00:04 UTC, kaze-st commented on server/src/routes/v1/file.routes.ts
> +
Can we move this code to a file named `FileExtension` and then into a  folder called `types`? We want to make sure this is usable for the rest of the code just in case.

2021-03-03 00:04 UTC, kaze-st commented on server/src/controllers/FileController.ts
>  		let callbackErr: any = null;
Add type to it and remove the comment above.

2021-03-03 04:20 UTC, kaze-st requested changes

2021-03-03 04:20 UTC, kaze-st commented on server/src/models/FileModel.ts
> +		mongoose.Schema.Types.String.checkRequired((v) => typeof v === 'string');
Can you try to move this to `BaseModel`? I want to make sure that this logic is shared across all models.

2021-03-03 20:05 UTC, npham24 commented on server/src/controllers/FileController.ts
>  		let callbackErr: any = null;
what is the type

2021-03-03 20:17 UTC, npham24 commented on server/src/models/FileModel.ts
> +		mongoose.Schema.Types.String.checkRequired((v) => typeof v === 'string');
BaseModel's getSchema is abstract so I'm not sure the best way to go about this

2021-03-03 21:46 UTC, kaze-st approved these changes
:shipit:

2021-03-03 21:46 UTC, merged